# Generated by Django 5.2.7 on 2025-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetails',
            options={'verbose_name': 'Product Detail', 'verbose_name_plural': 'Product Details'},
        ),
        migrations.AddField(
            model_name='productdetails',
            name='sku',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
