# Generated by Django 5.2.7 on 2025-10-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'Order Detail', 'verbose_name_plural': 'Order Details'},
        ),
    ]
