# Generated by Django 5.2.7 on 2025-10-08 07:53

import apps.reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(validators=[apps.reviews.models.validate_rating]),
        ),
    ]
